name: pr
on:
  pull_request:
    branches:
      - master

permissions:
  contents: write
  id-token: write

jobs:
  dependencies:
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yaml@main
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  alpha:
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@main
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    with:
      npmTag: alpha
      buildScript: build
      nodeVersion: 18
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}
