name: release
on:
  push:
    branches:
      - master

jobs:
  stable:
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@main
    with:
      releaseScript: release
      nodeVersion: 20
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}
