name: release
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write
  issues: write

jobs:
  dependencies:
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yaml@1c4632ccc198d4c9b34d9e6b3d556c6f245b4e69 # main
    if:
      github.event_name == 'pull_request' && github.event.pull_request.title != 'Upcoming Release
      Changes'
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  alpha:
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@1c4632ccc198d4c9b34d9e6b3d556c6f245b4e69 # main
    if:
      github.event_name == 'pull_request' && github.event.pull_request.title != 'Upcoming Release
      Changes'
    with:
      npmTag: alpha
      buildScript: build
      nodeVersion: 20
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  stable:
    if: github.ref == 'refs/heads/master'
    concurrency: ${{ github.workflow }}-${{ github.ref }}-release-stable
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@1c4632ccc198d4c9b34d9e6b3d556c6f245b4e69 # main
    with:
      releaseScript: release
      nodeVersion: 20
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}
